- name: Install Redis Repos
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enabling Redis 6.2v
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Updating Redis Listen address - /etc/redis.conf
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
      - /etc/redis/redis.conf
      - /etc/redis.conf

- name: Starting Redis Service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: true
