- name: Copy MongoDB Repo File
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: Updating MongoDB Listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB Server
  ansible.builtin.systemd_service:
    state: restarted
    name: mongod
    enabled: true
