- name: install nodejs
  ansible.builtin.yum:
    name: nodejs '18'
    state: latest

#echo -e "${colour} Enable NodeJs 18v ${nocolour}"
#dnf module disable nodejs -y  &>>${log_file}
#dnf module enable nodejs:18 -y  &>>${log_file}

#stat_check $?

#echo -e "${colour} Installing NodeJS ${nocolour}"
#dnf install nodejs -y  &>>${log_file}

#stat_check $?

#app_pre_setup

#echo -e "${colour} Installing NodeJS Dependencies ${nocolour}"
#npm install  &>>${log_file}

#systemd_setup
