- name: Update Prometheus Configuration File
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus Server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes